//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ApplicationData", "Person_Lab", "Person", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ApplicationData.Implementation.Person), "Lab", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ApplicationData.Implementation.Lab), true)]

#endregion

namespace ApplicationData.Implementation
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ApplicationDataObjectContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ApplicationDataObjectContext object using the connection string found in the 'ApplicationDataObjectContext' section of the application configuration file.
        /// </summary>
        public ApplicationDataObjectContext() : base("name=ApplicationDataObjectContext", "ApplicationDataObjectContext")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ApplicationDataObjectContext object.
        /// </summary>
        public ApplicationDataObjectContext(string connectionString) : base(connectionString, "ApplicationDataObjectContext")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ApplicationDataObjectContext object.
        /// </summary>
        public ApplicationDataObjectContext(EntityConnection connection) : base(connection, "ApplicationDataObjectContext")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Lab> Labs
        {
            get
            {
                if ((_Labs == null))
                {
                    _Labs = base.CreateObjectSet<Lab>("Labs");
                }
                return _Labs;
            }
        }
        private ObjectSet<Lab> _Labs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Person> People
        {
            get
            {
                if ((_People == null))
                {
                    _People = base.CreateObjectSet<Person>("People");
                }
                return _People;
            }
        }
        private ObjectSet<Person> _People;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Labs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLabs(Lab lab)
        {
            base.AddObject("Labs", lab);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the People EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPeople(Person person)
        {
            base.AddObject("People", person);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ApplicationData", Name="Lab")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Lab : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Lab object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="dateIssued">Initial value of the DateIssued property.</param>
        /// <param name="luckyNumber">Initial value of the LuckyNumber property.</param>
        /// <param name="person_Lab">Initial value of the Person_Lab property.</param>
        public static Lab CreateLab(global::System.Int32 id, global::System.DateTime dateIssued, global::System.Int32 luckyNumber, global::System.Int32 person_Lab)
        {
            Lab lab = new Lab();
            lab.Id = id;
            lab.DateIssued = dateIssued;
            lab.LuckyNumber = luckyNumber;
            lab.Person_Lab = person_Lab;
            return lab;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateIssued
        {
            get
            {
                return _DateIssued;
            }
            set
            {
                OnDateIssuedChanging(value);
                ReportPropertyChanging("DateIssued");
                _DateIssued = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateIssued");
                OnDateIssuedChanged();
            }
        }
        private global::System.DateTime _DateIssued;
        partial void OnDateIssuedChanging(global::System.DateTime value);
        partial void OnDateIssuedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BloodCellCount
        {
            get
            {
                return _BloodCellCount;
            }
            set
            {
                OnBloodCellCountChanging(value);
                ReportPropertyChanging("BloodCellCount");
                _BloodCellCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BloodCellCount");
                OnBloodCellCountChanged();
            }
        }
        private Nullable<global::System.Int32> _BloodCellCount;
        partial void OnBloodCellCountChanging(Nullable<global::System.Int32> value);
        partial void OnBloodCellCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> EyeLashes
        {
            get
            {
                return _EyeLashes;
            }
            set
            {
                OnEyeLashesChanging(value);
                ReportPropertyChanging("EyeLashes");
                _EyeLashes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EyeLashes");
                OnEyeLashesChanged();
            }
        }
        private Nullable<global::System.Decimal> _EyeLashes;
        partial void OnEyeLashesChanging(Nullable<global::System.Decimal> value);
        partial void OnEyeLashesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LuckyNumber
        {
            get
            {
                return _LuckyNumber;
            }
            set
            {
                OnLuckyNumberChanging(value);
                ReportPropertyChanging("LuckyNumber");
                _LuckyNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LuckyNumber");
                OnLuckyNumberChanged();
            }
        }
        private global::System.Int32 _LuckyNumber;
        partial void OnLuckyNumberChanging(global::System.Int32 value);
        partial void OnLuckyNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Person_Lab
        {
            get
            {
                return _Person_Lab;
            }
            set
            {
                OnPerson_LabChanging(value);
                ReportPropertyChanging("Person_Lab");
                _Person_Lab = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Person_Lab");
                OnPerson_LabChanged();
            }
        }
        private global::System.Int32 _Person_Lab;
        partial void OnPerson_LabChanging(global::System.Int32 value);
        partial void OnPerson_LabChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ApplicationData", "Person_Lab", "Person")]
        public Person Person
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Person>("ApplicationData.Person_Lab", "Person").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Person>("ApplicationData.Person_Lab", "Person").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Person> PersonReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Person>("ApplicationData.Person_Lab", "Person");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Person>("ApplicationData.Person_Lab", "Person", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ApplicationData", Name="Person")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Person : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Person object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Person CreatePerson(global::System.Int32 id, global::System.String name)
        {
            Person person = new Person();
            person.Id = id;
            person.Name = name;
            return person;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ApplicationData", "Person_Lab", "Lab")]
        public EntityCollection<Lab> Labs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Lab>("ApplicationData.Person_Lab", "Lab");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Lab>("ApplicationData.Person_Lab", "Lab", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
